#!/usr/bin/env node
/*
 * Website Content Planner — Build Script (Node, zero dependencies)
 *
 * Mirror of tools/build.ps1 for users who prefer Node. Uses only `fs` and `path`.
 *
 * Usage:
 *   node tools/build.js
 */
'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

function walk(dir, ext, out) {
  out = out || [];
  if (!fs.existsSync(dir)) return out;
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, ext, out);
    else if (e.isFile() && full.toLowerCase().endsWith('.' + ext)) out.push(full);
  }
  return out;
}

function concatDir(srcDir, ext) {
  const files = walk(srcDir, ext);
  if (files.length === 0) return null;
  files.sort(); // lexicographic full-path sort — matches PS version
  const parts = [];
  for (const f of files) {
    const rel = path.relative(srcDir, f).replace(/\\/g, '/');
    parts.push('/* ===== ' + rel + ' ===== */');
    // Strip exactly ONE trailing newline to avoid blank-line pileup at
    // boundaries. Intentional blank lines at end of file are preserved.
    let body = fs.readFileSync(f, 'utf8');
    if (body.endsWith('\r\n'))    body = body.slice(0, -2);
    else if (body.endsWith('\n')) body = body.slice(0, -1);
    parts.push(body);
  }
  return parts.join('\r\n');
}

function readOrFallback(srcDir, ext, fallbackFile, label) {
  const built = concatDir(srcDir, ext);
  if (built) {
    console.log('  ' + label + ': built from ' + path.relative(ROOT, srcDir));
    return built;
  }
  if (fs.existsSync(fallbackFile)) {
    console.log('  ' + label + ': fallback to ' + path.relative(ROOT, fallbackFile));
    return fs.readFileSync(fallbackFile, 'utf8');
  }
  throw new Error('No source for ' + label + ' (neither ' + srcDir + ' nor ' + fallbackFile + ' exists)');
}

function stamp() {
  const d = new Date();
  const pad = n => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + pad(d.getMonth()+1) + '-' + pad(d.getDate()) + ' ' +
         pad(d.getHours()) + ':' + pad(d.getMinutes()) + ':' + pad(d.getSeconds());
}

fs.mkdirSync(DIST, { recursive: true });
console.log('Building Website Content Planner...');

// --- JS ---
const p1  = readOrFallback(path.join(ROOT, 'src', 'part1'),  'js', path.join(ROOT, 'wcp-part1.js'),  'Part 1');
const p2a = readOrFallback(path.join(ROOT, 'src', 'part2a'), 'js', path.join(ROOT, 'wcp-part2a.js'), 'Part 2A');
const p2b = readOrFallback(path.join(ROOT, 'src', 'part2b'), 'js', path.join(ROOT, 'wcp-part2b.js'), 'Part 2B');

const jsHeader = '/*! Website Content Planner v1.0 — built ' + stamp() + '\r\n' +
                 ' *  Source: src/part1 + src/part2a + src/part2b\r\n' +
                 ' *  Do not edit this file directly — edit files under src/ and rebuild.\r\n' +
                 ' */';
const jsOut = [jsHeader, p1, p2a, p2b].join('\r\n');
fs.writeFileSync(path.join(DIST, 'wcp.js'), jsOut);
console.log('  -> dist/wcp.js (' + fs.statSync(path.join(DIST, 'wcp.js')).size.toLocaleString() + ' bytes)');

// --- CSS ---
const css1 = readOrFallback(path.join(ROOT, 'src', 'styles', 'part1'), 'css', path.join(ROOT, 'wcp-part1.css'), 'CSS Part 1');
const css2 = readOrFallback(path.join(ROOT, 'src', 'styles', 'part2'), 'css', path.join(ROOT, 'wcp-part2.css'), 'CSS Part 2');

const cssHeader = '/*! Website Content Planner v1.0 — built ' + stamp() + '\r\n' +
                  ' *  Source: src/styles/part1 + src/styles/part2\r\n' +
                  ' *  Do not edit this file directly — edit files under src/ and rebuild.\r\n' +
                  ' */';
const cssOut = [cssHeader, css1, css2].join('\r\n');
fs.writeFileSync(path.join(DIST, 'wcp.css'), cssOut);
console.log('  -> dist/wcp.css (' + fs.statSync(path.join(DIST, 'wcp.css')).size.toLocaleString() + ' bytes)');

console.log('Build complete.');
