# Website Content Planner - Build Script (PowerShell, zero dependencies)
#
# Reads:
#   src/part1/**/*.js       -> concatenated as IIFE block 1
#   src/part2a/**/*.js      -> concatenated as IIFE block 2
#   src/part2b/**/*.js      -> concatenated as IIFE block 3
#   src/styles/part1/**/*.css
#   src/styles/part2/**/*.css
#
# Writes:
#   dist/wcp.js             <- block 1 + block 2 + block 3
#   dist/wcp.css            <- part1 css + part2 css
#
# Fallback (Phase 0 only): if a part source folder is empty or missing,
# the original root-level file (wcp-part1.js etc.) is used in its place.
# Once Phases 1-4 finish, those root files are deleted and the fallback
# is a no-op.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File tools\build.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dist = Join-Path $root 'dist'
New-Item -ItemType Directory -Force -Path $dist | Out-Null

function Concat-Dir {
    param([string]$SrcDir, [string]$Ext)
    if (-not (Test-Path $SrcDir)) { return $null }
    $files = Get-ChildItem -Path $SrcDir -Recurse -File -Filter "*.$Ext" |
             Sort-Object FullName
    if ($files.Count -eq 0) { return $null }
    $sb = New-Object System.Text.StringBuilder
    foreach ($f in $files) {
        $rel = $f.FullName.Substring($SrcDir.Length + 1)
        [void]$sb.AppendLine(("/* ===== {0} ===== */" -f $rel))
        # Strip exactly ONE trailing newline (CRLF or LF) so concat doesn't create
        # extra blank lines at boundaries. Intentional blank lines at the end of
        # a source file are preserved.
        $body = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)
        if ($body.EndsWith("`r`n"))  { $body = $body.Substring(0, $body.Length - 2) }
        elseif ($body.EndsWith("`n")) { $body = $body.Substring(0, $body.Length - 1) }
        [void]$sb.Append($body)
        [void]$sb.AppendLine()
    }
    return $sb.ToString()
}

function Read-OrFallback {
    param([string]$SrcDir, [string]$Ext, [string]$FallbackFile, [string]$Label)
    $built = Concat-Dir -SrcDir $SrcDir -Ext $Ext
    if ($built) {
        Write-Host ("  {0}: built from {1}" -f $Label, $SrcDir)
        return $built
    }
    if (Test-Path $FallbackFile) {
        Write-Host ("  {0}: fallback to {1}" -f $Label, $FallbackFile) -ForegroundColor Yellow
        return [System.IO.File]::ReadAllText($FallbackFile, [System.Text.Encoding]::UTF8)
    }
    throw "No source for $Label (neither $SrcDir nor $FallbackFile exists)"
}

Write-Host "Building Website Content Planner..." -ForegroundColor Cyan

# --- JS ---
$p1  = Read-OrFallback "$root\src\part1"  'js' "$root\wcp-part1.js"  'Part 1'
$p2a = Read-OrFallback "$root\src\part2a" 'js' "$root\wcp-part2a.js" 'Part 2A'
$p2b = Read-OrFallback "$root\src\part2b" 'js' "$root\wcp-part2b.js" 'Part 2B'

$jsHeader = @"
/*! Website Content Planner v1.0 - built $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
 *  Source: src/part1 + src/part2a + src/part2b
 *  Do not edit this file directly - edit files under src/ and rebuild.
 */
"@
$jsOut = ($jsHeader, $p1, $p2a, $p2b) -join "`r`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText("$dist\wcp.js", $jsOut, $utf8NoBom)
$jsBytes = (Get-Item "$dist\wcp.js").Length
Write-Host ("  -> dist\wcp.js ({0:N0} bytes)" -f $jsBytes) -ForegroundColor Green

# --- CSS ---
$css1 = Read-OrFallback "$root\src\styles\part1" 'css' "$root\wcp-part1.css" 'CSS Part 1'
$css2 = Read-OrFallback "$root\src\styles\part2" 'css' "$root\wcp-part2.css" 'CSS Part 2'

$cssHeader = @"
/*! Website Content Planner v1.0 - built $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
 *  Source: src/styles/part1 + src/styles/part2
 *  Do not edit this file directly - edit files under src/ and rebuild.
 */
"@
$cssOut = ($cssHeader, $css1, $css2) -join "`r`n"
[System.IO.File]::WriteAllText("$dist\wcp.css", $cssOut, $utf8NoBom)
$cssBytes = (Get-Item "$dist\wcp.css").Length
Write-Host ("  -> dist\wcp.css ({0:N0} bytes)" -f $cssBytes) -ForegroundColor Green

Write-Host "Build complete." -ForegroundColor Cyan
